version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      - echo "Logging in to Amazon ECR..."
  build:
    commands:
      - echo "Build phase started on `date`"
      - echo "Building the application..."
      # Add your actual build commands here
      # Example for a Node.js app:
      # - npm install
      # - npm run build
      # Example for a simple web app:
      # - echo "No build steps required for static files"
  post_build:
    commands:
      - echo "Post-build phase completed on `date`"

artifacts:
  files:
    - '**/*'
  name: build-artifacts